### ISSUE TITLE
Getting "You're not authorized to share on <url>" after my terminal crashed

### ISSUE THREAD

**Issue by rgoliveira** [vitorbaptista/shellshare#36]
I was streaming my Vim session and suddenly strange things started to appear on the screen, and among these, some message saying my connection was lost (or something similar, I didn't save it, sorry :cry:).

And now, if I try to use the same room again, it errors with:
```
$ python shellshare -r rgoliveira
Current terminal size is 42x167.
It's too big to be viewed on smaller screens.
You can resize it anytime.
Sharing terminal in https://shellshare.net/r/rgoliveira
$
ERROR: You're not authorized to share on https://shellshare.net/r/rgoliveira.
ERROR: Exit shellshare and try again later.

End of transmission.
```

Edit: just remembered that it crashed when I was trying out some different color schemes on Vim. Maybe something related to this caused the first issue (maybe the strange sequences used to generate colors?).

**Comment by rgoliveira** [comment]
So it happened again. Now I was able to get the error message. Something like:
```
Unhandled exception in thread started by <function stream file at 0x7f4c5a78eaa0>
Traceback (most recent call last):
File "../streaming/shellshare", line 81, in stream file success = post(conn, url, encoded_str, room, password)
File "../streaming/shellshare", line 62, in post raise e socket.error: [Errno 32] Broken pipe
```

Here's the screen capture of my vim at the moment it happened:
![erro shellshare](https://cloud.githubusercontent.com/assets/1731173/17086939/0d01f632-51d5-11e6-9211-8a5ca165498a.png)

**Comment by vitorbaptista** [comment]
@rgoliveira Sorry for the super late reply. Do you know if you had the latest `shellshare`? Those errors were quite common, but this PR solved them for me https://github.com/vitorbaptista/shellshare/pull/35. After that, `shellshare` has been very stable

**Comment by vitorbaptista** [comment]
Ah! Generally, if you want to share on a custom URL, you'd also want to create a password for it:

> Can I broadcast to a custom link?
> 
> Yes. You can broadcast to a named room secured with a password by calling shellshare as:
> ```
> $ wget -qO shellshare http://get.shellshare.net
> $ python shellshare --room MY-ROOM --password MY-PASS
> Sharing terminal in https://shellshare.net/r/MY-ROOM
> $ # ...
> $ exit
> End of transmission.
> ```
> You don't have to set a password but, if you don't, you won't be able to transmit to the same room later. The rooms are deleted when they have no activity for more than a day.

This is a common surprise which I want to fix. Just created https://github.com/vitorbaptista/shellshare/issues/38 to track it. If you want to give it a go, pull requests are super welcome :wink:

**Comment by rgoliveira** [comment]
Hey, @vitorbaptista! No worries. Yeah, at one point I figured I should probably be using a password, but haven't had the time to test it again.

**Comment by rgoliveira** [comment]
I don't have much free time right now, but I'll keep an eye on this. Thanks for the reply!

**Comment by vitorbaptista** [comment]
Great, @rgoliveira. I'm closing this now, then. Feel free to reopen (or create a new one) as needed. Have a good weekend!
