### ISSUE TITLE
Installing dependencies failing

### ISSUE THREAD

**Issue by gityunus** [vitorbaptista/shellshare#65]
Hi, 

I am getting the following Traceback error on Windows, when attempting to download and install dependencies via Git Bash. Any help please?

Traceback (most recent call last):
  File "shellshare", line 185, in <module>
    url_req.urlretrieve(script_url, script_path)
  File "C:\Python38\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python38\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Python38\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Python38\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Python38\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by dpshelio** [comment]
I've found this is due to the server not accepting a query without a user agent (and had already been proposed a fix on #64). This can be fixed on the server-side, or in the shellshare script when calling the server. I've opened PR #66 that fixes for python3 only.
You could try to test it using my changes by:
```bash
curl -sLo shellshare https://raw.githubusercontent.com/dpshelio/shellshare/win_403_error_py3/public/bin/shellshare
python shellshare
```

**Comment by gityunus** [comment]
Great, this worked!
