### ISSUE TITLE
shellshare doesn't share anything and won't exit

### ISSUE THREAD

**Issue by larsks** [vitorbaptista/shellshare#67]
I'm trying to run shellshare on Fedora 33 (python 3.9.1). It runs without errors, prints a URL, and starts a new shell session, but when opened in the browser there is nothing but a blank screen with a blinking cursor in the upper left. Activity in the local shell never shows up in the browser.

When I attempt to `exit` the shellshare-spawned shell, it hangs. Hitting CTRL-C produces the following traceback:

```
^CTraceback (most recent call last):
  File "/home/lars/bin/shellshare", line 202, in <module>
    delete(args.server, room, args.password)
  File "/home/lars/bin/shellshare", line 131, in delete
    conn.request('DELETE', '/%s' % room, {}, headers)
  File "/usr/lib64/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib64/python3.9/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/lib64/python3.9/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib64/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
KeyboardInterrupt
```

**Comment by vitorbaptista** [comment]
Many years later, I think this is fixed. Shellshare was entirely rewritten.
