### ISSUE TITLE
proper installation and use of Shellshare under MS Windows 10

### ISSUE THREAD

**Issue by edmundlaugasson** [vitorbaptista/shellshare#68]
Looks like now v1.1.0 has Windows support? How to properly install and use under Windows? Noticed, that %appdata%\Local\Microsoft\WindowsApps is in path, perhaps download [shellshare](https://raw.githubusercontent.com/vitorbaptista/shellshare/master/public/bin/shellshare) and [script.exe](https://github.com/vitorbaptista/shellshare/raw/master/public/bin/script.exe C:\Users\student\AppData\Local\Microsoft\WindowsApps\script.exe) there? How to run then?

**Comment by edmundlaugasson** [comment]
nice way to solve issues - just close them...

**Comment by edmundlaugasson** [comment]
Just for others:
- python must be installed
- created environment variable for user
  - super+R -> rundll32 sysdm.cpl,EditEnvironmentVariables
  - e.g. variable with name shellshare
  - value for variable:
    -  "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe" H:\scripts\shellshare
  - later you can run it from CLI ([cmd](https://en.wikipedia.org/wiki/Cmd.exe)) like %shellshare%
  - [clink](https://mridgers.github.io/clink/) is also useful for [cmd](https://en.wikipedia.org/wiki/Cmd.exe) users

**Comment by edmundlaugasson** [comment]
Still I face with issues:
```
'tput' is not recognized as an internal or external command,
operable program or batch file.
'tput' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "H:\scripts\shellshare", line 190, in <module>
    size = terminal_size()
  File "H:\scripts\shellshare", line 58, in terminal_size
    cols = int(cols.stdout.read().strip())
ValueError: invalid literal for int() with base 10: b''
```
Tried to resize [cmd](https://en.wikipedia.org/wiki/Cmd.exe) - didn't help..

**Comment by mikerenfro** [comment]
I'd tested this originally with Git Bash in Windows, which includes its own `tput` and related executables. I also used Anaconda Python, which wouldn't require administrative rights, but any installed Python available in the PATH should work just as well.

**Comment by edmundlaugasson** [comment]
The question is related with MS Windows command line and not Bash in Windows. When we try to use built-in CLI in MS Windows, then shellshare won't work with previously mentioned error messages. But the claim in #61 was, that shellshare will work without Cygwin emulation now, but actually it does not. We can also use WSL, which enables Bash in MS Windows, but then it's not actually MS Windows anymore, it is Linux subsystem, which is in case of Git Bash also. My main concern is native Windows CLI, what was also the claim of #61 ...

**Comment by mikerenfro** [comment]
Shellshare isn't my project by any means, I'm just someone who wanted to use it under Windows in some Software Carpentry workshops, which already use Git Bash. Shellshare definitely needs some utilities standard for Unix environments like `tput`, and until those are replaced, it won't be a 100% fit for standard Windows. The Python parts of Shellshare are _incredibly_ lean, and it relies heavily on other Unix utilities to do the real work of screen management and recording.

@dpshelio did some PowerShell work in #61 , but I don't think that got integrated in, since he was also willing to go with a Git Bash environment for his Windows users, if I recall correctly.

So the project went from "doesn't support non-Cygwin Windows at all (due to missing `tput` and `script`)" to "supports Windows without Cygwin (if you've got Git Bash for `tput`, since we can download a compatible copy of `script` on the fly)".
